require("dhanifudin.plugins.install")
require("dhanifudin.plugins.lsp")
require("dhanifudin.plugins.lspsaga")
require("dhanifudin.plugins.treesitter")
-- require("dhanifudin.plugins.easymotion")
-- require("dhanifudin.plugins.leap")
require("dhanifudin.plugins.lualine")
require("dhanifudin.plugins.blankline")
require("dhanifudin.plugins.telescope")
require("dhanifudin.plugins.formatter")
