require("dhanifudin.plugins.blankline")
require("dhanifudin.plugins.dial")
require("dhanifudin.plugins.formatter")
require("dhanifudin.plugins.gitsigns")
require("dhanifudin.plugins.gruvbox")
-- require("dhanifudin.plugins.lsp")
-- require("dhanifudin.plugins.lspsaga")
require("dhanifudin.plugins.lualine")
require("dhanifudin.plugins.treesitter")
require("dhanifudin.plugins.yoink")
require("dhanifudin.plugins.zenmode")