if empty(glob('~/.vim/autoload/plug.vim'))
  echo 'Installing vim-plug...'
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  echo 'Run :PlugInstall to install plugins'
endif

let g:ssh_session = $SSH_TTY

call plug#begin('~/.vim/plugged')
if empty(g:ssh_session)
  source $HOME/.vim/plugins.local.vim
else
  source $HOME/.vim/plugins.ssh.vim
endif
call plug#end()
