if empty(glob('~/.vim/autoload/plug.vim'))
  echo 'Installing vim-plug...'
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  echo 'Run :PlugInstall to install plugins'
endif

call plug#begin('~/.vim/plugged')
" completion
Plug 'ackyshake/VimCompletesMe'
Plug 'docunext/closetag.vim'
Plug 'jiangmiao/auto-pairs'
Plug 'vim-scripts/cmdline-completion'

" eyecandy
Plug 'morhetz/gruvbox'
Plug 'vim-airline/vim-airline'
Plug 'airblade/vim-gitgutter'
Plug 'Yggdroot/indentLine'

" tpope
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-vinegar'

" textobject
Plug 'kana/vim-textobj-user'
Plug 'kana/vim-textobj-entire'
Plug 'Julian/vim-textobj-variable-segment'

" ctrlp
Plug 'ctrlpvim/ctrlp.vim'
Plug 'tacahiroy/ctrlp-funky'
Plug 'fisadev/vim-ctrlp-cmdpalette'
Plug 'ompugao/ctrlp-history'

" navigation
Plug 'christoomey/vim-tmux-navigator'
Plug 'easymotion/vim-easymotion'

" misc
Plug 'editorconfig/editorconfig-vim'
Plug 'mbbill/undotree'
Plug 'mileszs/ack.vim'
Plug 'roman/golden-ratio'
Plug 'svermeulen/vim-easyclip'
Plug 'wakatime/vim-wakatime'
call plug#end()
